### ISSUE TITLE
Don't show pending users as previous member

### ISSUE THREAD

**Issue by tunnell** [RiceAstroparticleLab/xenon-users-web#22]
The issue is that people who have been requested but aren't approved are not active yet.  In the list of 'active' or 'pending' users shown for each institute, they are shown as 'pending'.  Instead of adding a third category, can we hide pending users here?  Or show them as pending somehow?

See (at moment):

https://xenonnt.lngs.infn.it/shifts/institutes/MPIK%20Heidelberg

**Comment by ymart2** [comment]
Fixed, see commit `9da9e85`.
